version: '3'
services: 
  indy:
    build: ./indy
    image: "commonjava/smoke-indy:latest"
    ports:
      - "8080:8080"
  auditquery:
    build: ./auditquery
    image: "commonjava/smoke-aq:latest"
    ports:
      - "8082:8082"